# -Indexing

In [1]:
#make a string
a= "Samosa Pakora"
a

'Samosa Pakora'

In [2]:
a[0]
#counting will star from 0 to onwards in python 

'S'

In [3]:
a[1]

'a'

In [4]:
a[2]

'm'

In [5]:
a[6]
#it will print a space

' '

In [7]:
len(a)
#it will show the number of index in our string

13

In [8]:
a[0:6]
#the last no will be excludes like i ask for letters from 0 to 6 but it will print from 0 to 5 letters 

'Samosa'

In [10]:
a[1:8]
#here P is 7th character as we strat counting from 0 

'amosa P'

In [11]:
a[0:13] #here if we count from 0 to 13 it will be total 14 characters here 13 no is exclusive and count complterd from 0 to 12 total as 13 

'Samosa Pakora'

In [13]:
a[-2]
#here it starts from right side and will start from number (-1)

'r'

In [15]:
a[-1:-6]

#here it will not print any thing 

''

In [19]:
a[-6:-1]
#here we see the writing sequence in string will remain same from right to left
#also -1 no is "a" but it will not print here as last no is exclude

'Pakor'

In [20]:
a[-6:0]

''

In [21]:
a[-6:13]

'Pakora'

In [22]:
food= "birYani"
food

'birYani'

## String Methods


In [25]:
food


'birYani'

In [26]:
len(food)

7

In [27]:
# Capitalize 
food.capitalize()

'Biryani'

In [28]:
#Upper case letters
food.upper()

'BIRYANI'

In [29]:
#lower case letters
food.lower()

'biryani'

In [30]:
#replace
food.replace("b", "sh")

'shirYani'

In [31]:
#counting a specific alphabet in a string 
name = "baba_aammar with Dr aamar tufail"
name

'baba_aammar with Dr aamar tufail'

In [32]:
name.count("a")

9

In [33]:
name.count("D")

1

In [34]:
#how to find a number of index in string
name = "baba_aammar with Dr aamar tufail"
name


'baba_aammar with Dr aamar tufail'

In [37]:
name.find("t")

14

In [38]:
# how to split a string
food = "i love samosa , pakora , raita, biryani and karahi"
food

'i love samosa , pakora , raita, biryani and karahi'

In [40]:
food.split(",")

['i love samosa ', ' pakora ', ' raita', ' biryani and karahi']

# Basic data Structure in Python
## 1-Tuple
## 2-List
## 3-Dictionaries
## 4-Set

 ### Tuole
 - Ordered collection of elements 
 - eclosed in () round braces/ paranthesis
 - Different kind of elements can be stored (elements like int, float , string, boolean{true, false})
 - Once elements are stored you can not change or replace them (Unmutatable) 

In [41]:
tup1 = (1,"python" , True , 2.5)
tup1

(1, 'python', True, 2.5)

In [42]:
#type of a tuple 
type(tup1)


tuple

### -indexing in tuple

In [43]:
tup1[1]


'python'

In [44]:
tup1[0]

1

In [47]:
tup1[0:6]

(1, 'python', True, 2.5)

In [48]:
tup1[0:3] # last element is exclusive

(1, 'python', True)

In [50]:
#length of tuple
len(tup1)

4

In [51]:
tup2 = (2, "baba ammar", 3.5, False )
tup2


(2, 'baba ammar', 3.5, False)

In [54]:
# concatinate ( TO add two or more tuple)
tup1+tup2

(1, 'python', True, 2.5, 2, 'baba ammar', 3.5, False)

In [55]:
#concatinate + repeat 
tup1*3 + tup2

(1,
 'python',
 True,
 2.5,
 1,
 'python',
 True,
 2.5,
 1,
 'python',
 True,
 2.5,
 2,
 'baba ammar',
 3.5,
 False)

In [56]:
tup1*2 + tup2

(1, 'python', True, 2.5, 1, 'python', True, 2.5, 2, 'baba ammar', 3.5, False)

In [57]:
tup3 = (20, 50, 60, 80, 96)
tup3


(20, 50, 60, 80, 96)

In [58]:
max(tup3)

96

In [59]:
min(tup3)

20

In [60]:
tup3*2

(20, 50, 60, 80, 96, 20, 50, 60, 80, 96)

---

**mark down it and add three dashes - will creat space line** 

## List
- ordered collection of elements 
- enclosed in [] square barckets
- Mutateable, you can change the values 

In [61]:
list1 = [2, "baba ammar" , False]
list1


[2, 'baba ammar', False]

In [63]:
type(list1)

list

In [64]:
len(list1)

3

In [65]:
list1[2]

False

In [68]:
list2 = [3, 5, "Aammar", "Codanics", 478, 53.2, True]
list2

[3, 5, 'Aammar', 'Codanics', 478, 53.2, True]

In [69]:
list1 + list2

[2, 'baba ammar', False, 3, 5, 'Aammar', 'Codanics', 478, 53.2, True]

In [70]:
list1*2

[2, 'baba ammar', False, 2, 'baba ammar', False]

In [75]:
list1

[2, 'baba ammar', False]

In [76]:
list1.reverse()
list1

[False, 'baba ammar', 2]

In [78]:
list1.append("codanics youtube channel")
list1

[False,
 'baba ammar',
 2,
 'codanics youtube channel',
 'codanics youtube channel']

In [81]:
list1.count(False)


1

In [82]:
list3 = [20,30,40,50,60,52,562,488,2485]
list3


[20, 30, 40, 50, 60, 52, 562, 488, 2485]

In [83]:
len(list3)

9

In [84]:
#sorting a List
list3.sort()
list3


[20, 30, 40, 50, 52, 60, 488, 562, 2485]

In [85]:
#repeat
list3*3


[20,
 30,
 40,
 50,
 52,
 60,
 488,
 562,
 2485,
 20,
 30,
 40,
 50,
 52,
 60,
 488,
 562,
 2485,
 20,
 30,
 40,
 50,
 52,
 60,
 488,
 562,
 2485]

In [86]:
list2+list3

[3,
 5,
 'Aammar',
 'Codanics',
 478,
 53.2,
 True,
 20,
 30,
 40,
 50,
 52,
 60,
 488,
 562,
 2485]

In [87]:
lists= list1 +list2
lists

[False,
 'baba ammar',
 2,
 'codanics youtube channel',
 'codanics youtube channel',
 3,
 5,
 'Aammar',
 'Codanics',
 478,
 53.2,
 True]

## 3- Dictionaries
- AN unirdered collection of element
- Key and value
- Curly braces/ braces {}
- Mutateable , you can change the value 

In [89]:
#Food and thier prices 
food1= {"Samosa" : 30, "Pakora" : 100, "Raita" : 20, "Salad" : 50, "Chicken Rolls": 30,}
food1

{'Samosa': 30, 'Pakora': 100, 'Raita': 20, 'Salad': 50, 'Chicken Rolls': 30}

In [90]:
type(food1)

dict

In [92]:
#extract data 
keys= food1.keys()
keys

dict_keys(['Samosa', 'Pakora', 'Raita', 'Salad', 'Chicken Rolls'])

In [93]:
values = food1.values()
values

dict_values([30, 100, 20, 50, 30])

In [95]:
#adding new element
food1["Tikki"]=10
food1

{'Samosa': 30,
 'Pakora': 100,
 'Raita': 20,
 'Salad': 50,
 'Chicken Rolls': 30,
 'Tikki': 10}

In [96]:
#updating a values
food1["Tikki"]= 15
food1

{'Samosa': 30,
 'Pakora': 100,
 'Raita': 20,
 'Salad': 50,
 'Chicken Rolls': 30,
 'Tikki': 15}

In [97]:
food2 = {"Dates": 50, "Chocolates":200, "Sawayyan":1000}
food2

{'Dates': 50, 'Chocolates': 200, 'Sawayyan': 1000}

In [103]:
#Concatinate
food1.update(food2)
food1


{'Samosa': 30,
 'Pakora': 100,
 'Raita': 20,
 'Salad': 50,
 'Chicken Rolls': 30,
 'Tikki': 15,
 'Dates': 50,
 'Chocolates': 200,
 'Sawayyan': 1000}

## 4-Sets
- An unordered and un-indexed
- Curly braces {} are used 
- no  duplicates allowed 

In [109]:
s1= {1, 2, 2.2, 5, "Codanics", "Faisalabad", True}
s1
# here we see that boolean operator dosent print in sets 

{1, 2, 2.2, 5, 'Codanics', 'Faisalabad'}

In [111]:
s1.add("codanics")
s1

{1, 2, 2.2, 5, 'Codanics', 'Faisalabad', 'codanics'}

In [112]:
s1.add("Faisalabad")
s1


{1, 2, 2.2, 5, 'Codanics', 'Faisalabad', 'codanics'}

In [113]:
s1.remove("codanics")
s1

{1, 2, 2.2, 5, 'Codanics', 'Faisalabad'}

In [7]:
import numpy as np
a = np.array([1,1,1])
a
b= np.array([[1,1,1,1], [2,2,2,2], [3,3,3,3]])
b

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [8]:
type(a)

numpy.ndarray

In [9]:
len(a)

3

In [10]:
c=np.zeros(3)
c

array([0., 0., 0.])

In [27]:
d=np.ones(5, dtype=np.float64)
d

array([1., 1., 1., 1., 1.])

In [28]:
d=np.ones(5, dtype=np.int64)
d

array([1, 1, 1, 1, 1], dtype=int64)

In [14]:
f=np.empty(2)
f

array([8.00277278e+100, 1.58668671e-295])

In [15]:
#range
q=np.arange(8)
q

array([0, 1, 2, 3, 4, 5, 6, 7])

In [17]:
w=np.arange(2,20)
w

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [21]:
e=np.arange(2,22,3)
e

array([ 2,  5,  8, 11, 14, 17, 20])

In [20]:
#linearly spaced arrays 
r= np.linspace(0,10, num=5) # mene 0 se 10 tak jana hai total 5 numbers me ese k beech ka distance brabar ho   
r

array([ 0. ,  2.5,  5. ,  7.5, 10. ])